### ISSUE TITLE
자바에서 enum 의 비교는 '==' 인가? 'equals' 인가?

### ISSUE THREAD

**Issue by LenKIM** [LenKIM/everyone-is-effective-java-study#2]
![image](https://user-images.githubusercontent.com/22192085/72310935-6d18fc80-36c6-11ea-878c-d9d264bb8943.png)

**Comment by LenKIM** [comment]
<참고 링크>
https://docs.oracle.com/javase/8/docs/api/
요기 정의 해놓은 걸 보면 enum는 class가 맞아요!

 하지만
https://docs.oracle.com/javase/specs/jls/se8/jls8.pdf
요기 의 8.9 보심 우리가 대체적으로 사용패턴은 enum의 상수를 비교할 때는 ==를 쓰라고 합니다.

결론적으로, (==, equals)모두 포함하는 Objects.equals 를 쓰는 건 어떨까요??ㅎㅎ

**Comment by kimth0719** [comment]
https://stackoverflow.com/questions/1750435/comparing-java-enum-members-or-equals
결론은
Both are technically correct. If you look at the source code for .equals(), it simply defers to ==.
I use ==, however, as that will be null safe.
